project_id = "yffdyyjugrzyqdvtjnho"

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.verify-init-data]
verify_jwt = false

[functions.set-admin]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.create-admin]
verify_jwt = false